export const tagTypeOptions = [
  "TOPIC",
  "EMOTION",
  "ACTION",
  "VALUE",
  "TIME",
  "PERSON",
  "VIRTUE",
  "VICE",
  "STATE",
  "RELATIONSHIP",
  "WORK",
  "SPIRITUAL",
  "POLITICS",
  "SOCIETY",
  "NATURE",
  "PLACE",
  "ERA",
  "EVENT",
  "ART",
  "SCIENCE",
  "FAITH_TRADITION",
] as const

export type TagTypeOption = (typeof tagTypeOptions)[number]

export const starterTagSeed: {
  name: string
  type: TagTypeOption
  description: string
}[] = [
  { name: "Wisdom", type: "TOPIC", description: "Insight, judgment, and thoughtful understanding." },
  { name: "Truth", type: "TOPIC", description: "Honesty, reality, and what is true." },
  { name: "Freedom", type: "TOPIC", description: "Liberty, autonomy, and independence." },
  { name: "Justice", type: "TOPIC", description: "Fairness, rights, and moral order." },
  { name: "Hope", type: "EMOTION", description: "Optimism and expectation of better outcomes." },
  { name: "Grief", type: "EMOTION", description: "Sorrow in response to loss." },
  { name: "Joy", type: "EMOTION", description: "Happiness, delight, and uplift." },
  { name: "Fear", type: "EMOTION", description: "Anxiety, danger, and uncertainty." },
  { name: "Change", type: "ACTION", description: "Transformation, reform, and movement." },
  { name: "Resistance", type: "ACTION", description: "Defiance, refusal, and standing firm." },
  { name: "Service", type: "ACTION", description: "Helping others through work or duty." },
  { name: "Reflection", type: "ACTION", description: "Deliberate thought and self-examination." },
  { name: "Integrity", type: "VALUE", description: "Moral consistency and ethical conduct." },
  { name: "Discipline", type: "VALUE", description: "Self-control, order, and consistency." },
  { name: "Compassion", type: "VALUE", description: "Care for the suffering of others." },
  { name: "Responsibility", type: "VALUE", description: "Duty, accountability, and ownership." },
  { name: "Youth", type: "TIME", description: "Early life, growth, and beginnings." },
  { name: "Old Age", type: "TIME", description: "Later life, reflection, and aging." },
  { name: "Memory", type: "TIME", description: "The past, remembrance, and recall." },
  { name: "Legacy", type: "TIME", description: "What remains after a life or action." },
  { name: "Leader", type: "PERSON", description: "Leadership, influence, and guidance." },
  { name: "Friend", type: "PERSON", description: "Companionship, trust, and closeness." },
  { name: "Teacher", type: "PERSON", description: "Instruction, mentorship, and learning." },
  { name: "Child", type: "PERSON", description: "Innocence, growth, and dependence." },
  { name: "Courage", type: "VIRTUE", description: "Bravery in the face of fear or danger." },
  { name: "Humility", type: "VIRTUE", description: "Modesty, restraint, and lack of arrogance." },
  { name: "Patience", type: "VIRTUE", description: "Endurance, calm waiting, and restraint." },
  { name: "Forgiveness", type: "VIRTUE", description: "Letting go of resentment and blame." },
  { name: "Pride", type: "VICE", description: "Excessive self-importance or vanity." },
  { name: "Greed", type: "VICE", description: "Excessive desire for wealth or gain." },
  { name: "Envy", type: "VICE", description: "Resentment of another's success or fortune." },
  { name: "Hatred", type: "VICE", description: "Deep hostility, bitterness, or contempt." },
  { name: "Peace", type: "STATE", description: "Inner calm, stillness, and harmony." },
  { name: "Despair", type: "STATE", description: "Loss of hope and discouragement." },
  { name: "Wonder", type: "STATE", description: "Awe, curiosity, and amazement." },
  { name: "Loneliness", type: "STATE", description: "Isolation, solitude, and absence of connection." },
  { name: "Friendship", type: "RELATIONSHIP", description: "Mutual trust, loyalty, and affection." },
  { name: "Family", type: "RELATIONSHIP", description: "Kinship, belonging, and home ties." },
  { name: "Marriage", type: "RELATIONSHIP", description: "Partnership, commitment, and shared life." },
  { name: "Mentorship", type: "RELATIONSHIP", description: "Guidance from one person to another." },
  { name: "Work Ethic", type: "WORK", description: "Commitment, effort, and diligence in work." },
  { name: "Ambition", type: "WORK", description: "Drive, aspiration, and pursuit of achievement." },
  { name: "Failure", type: "WORK", description: "Setbacks, lessons, and unmet goals." },
  { name: "Education", type: "WORK", description: "Learning, study, and intellectual development." },
  { name: "Faith", type: "SPIRITUAL", description: "Trust in the divine, meaning, or unseen." },
  { name: "Prayer", type: "SPIRITUAL", description: "Spiritual appeal, devotion, or communion." },
  { name: "Meditation", type: "SPIRITUAL", description: "Silence, contemplation, and inner focus." },
  { name: "Soul", type: "SPIRITUAL", description: "Inner being, spirit, and essence." },
  { name: "Democracy", type: "POLITICS", description: "Public participation and representative power." },
  { name: "Liberty", type: "POLITICS", description: "Civil freedom and protection from oppression." },
  { name: "Equality", type: "POLITICS", description: "Equal dignity, rights, and standing." },
  { name: "Revolution", type: "POLITICS", description: "Radical political or social change." },
  { name: "Culture", type: "SOCIETY", description: "Shared customs, values, and collective identity." },
  { name: "Humanity", type: "SOCIETY", description: "Human nature, solidarity, and common life." },
  { name: "Duty", type: "SOCIETY", description: "Obligation to others, society, or principle." },
  { name: "Gender", type: "SOCIETY", description: "Social and personal dimensions of gender." },
  { name: "Earth", type: "NATURE", description: "Land, world, and physical existence." },
  { name: "Sea", type: "NATURE", description: "Oceans, depth, and flowing life." },
  { name: "Sky", type: "NATURE", description: "Heavens, openness, and vastness." },
  { name: "Trees", type: "NATURE", description: "Growth, rootedness, and living nature." },
  { name: "Home", type: "PLACE", description: "Belonging, shelter, and personal place." },
  { name: "Village", type: "PLACE", description: "Small communities and rural life." },
  { name: "City", type: "PLACE", description: "Urban life, crowds, and modern society." },
  { name: "India", type: "PLACE", description: "India as a cultural, historical, or national setting." },
  { name: "Ancient World", type: "ERA", description: "Antiquity, origins, and early civilizations." },
  { name: "Medieval Age", type: "ERA", description: "The medieval period and its worldview." },
  { name: "Modern Era", type: "ERA", description: "Modernity, progress, and contemporary change." },
  { name: "Future Age", type: "ERA", description: "What lies ahead beyond the present." },
  { name: "Birth", type: "EVENT", description: "Beginnings, arrival, and new life." },
  { name: "Death", type: "EVENT", description: "Mortality, endings, and passing away." },
  { name: "Victory", type: "EVENT", description: "Triumph, success, and decisive achievement." },
  { name: "War", type: "EVENT", description: "Conflict, violence, and national struggle." },
  { name: "Poetry", type: "ART", description: "Verse, poetic expression, and lyrical language." },
  { name: "Music", type: "ART", description: "Sound, rhythm, and musical expression." },
  { name: "Literature", type: "ART", description: "Writing, books, and literary imagination." },
  { name: "Cinema", type: "ART", description: "Film, visual storytelling, and performance." },
  { name: "Reason", type: "SCIENCE", description: "Logic, evidence, and rational thought." },
  { name: "Technology", type: "SCIENCE", description: "Tools, innovation, and applied knowledge." },
  { name: "Medicine", type: "SCIENCE", description: "Healing, health, and medical practice." },
  { name: "Mathematics", type: "SCIENCE", description: "Numbers, structure, and abstract reasoning." },
  { name: "Hinduism", type: "FAITH_TRADITION", description: "Ideas and quotations rooted in Hindu traditions." },
  { name: "Buddhism", type: "FAITH_TRADITION", description: "Ideas and quotations rooted in Buddhist traditions." },
  { name: "Christianity", type: "FAITH_TRADITION", description: "Ideas and quotations rooted in Christian traditions." },
  { name: "Stoicism", type: "FAITH_TRADITION", description: "Ideas and quotations rooted in Stoic philosophy." },
]

export const starterTagSeedText = starterTagSeed
  .map((item) => `${item.name}||${item.type}|${item.description}`)
  .join("\n")
